"""add deleted_at to prompts

Revision ID: 4d3806db0011
Revises: 415a03a80544
Create Date: 2026-02-09 07:30:27.092747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3806db0011'
down_revision: Union[str, Sequence[str], None] = '415a03a80544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_prompts_deleted_at'), 'prompts', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_deleted_at'), table_name='prompts')
    op.drop_column('prompts', 'deleted_at')
    # ### end Alembic commands ###
