name: Deploy to Dev Server

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd ~/project/prompthub
          git pull
          docker compose down
          docker compose up -d --build
          docker image prune -f
